Add Travis CI job 38.1 report (SUCCESSFUL)
Total failed sketch builds: 0

Total warnings: 0

Total board issues: 0

Total library issues: 0

Job log: https://travis-ci.org/per1234/PalatisSoftPWM/jobs/476935233

Commit: https://github.com/per1234/PalatisSoftPWM/commit/6a1435c675fb83d217d03fb33c2dc7308fb65286

Fix incorrect definition of SOFTPWM_DEFINE_PIN63_CHANNEL

Incorrect register name "DDRK1" caused compilation to fail when SOFTPWM_DEFINE_PIN63_CHANNEL or SOFTPWM_DEFINE_PINA9_CHANNEL macros were used:

error: 'DDRK1' was not declared in this scope

[skip ci]